// 1. Handle authentication using local storage.

// 2. Create a Ul as shown in Figma, and make 2 pages - signup and profile. 

// 3. On clicking signup, use local storage to create the state of the user - it should contain all the details taken in signup.

// 4. The state of the user saved in localstorage should contain all the properties of the user, plus should also consist of an access token - let this access token be a random 16-byte string generated by you randomly.

// 5. Once there is a state of the user in the local storage, redirect the user to a page called /profile. Display the user's details there.

// 6. On clicking the logout button, set the local storage back to null and also get rid of the access token.

// 7. Using scripts ensure that when a user manually tries to go to /profile, if the local storage does not contain the accesstoken the user is redirected to the signup page.

// 8. Similarly if the localstorage has an accesstoken and tries to go to the signup page, using scripts ensures that the user
// can't do so and is redirected to the profile page.

//  9. Show success and errors as well as shown in the UL. All fields are mandatory for signup and similarly on successfully signing up show the message in green text and then redirect to /profile


// figma link
// https://www.figma.com/file/GWUrnugwWlzzxjMJewgoR8/Contest?type=design&node-id=0-1
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



/// Links
const signUpLink = document.getElementById("sign-up-link");
const profileLink = document.getElementById("profile-link");

/// form details
const username = document.getElementById("username");
const email = document.getElementById("email");
const password = document.getElementById("password");
const password2 = document.getElementById("password-2");
const signUpBtn = document.getElementById("signUp-btn");

/// error/success texts
const errorText = document.getElementById("error-text");
const successText = document.getElementById("error-text");

/// function to check valid mail
function checkMail(email){
    // skipping this method
}
function generateToken(){
    const characters ='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz0123456789';
    let res = '';
    let length = characters.length;
    for(let i = 1; i<=16; i++){
        res += characters.charAt(Math.floor(Math.random()*length));
    }
    return res;
}

signUpBtn.addEventListener("click", (e) => {
  e.preventDefault();
  if (
    username.value === "" ||
    email.value === "" ||
    password.value === "" ||
    password2.value === ""
  ) {
    errorText.innerHTML = `All fields are mandatory*`;
    return;
  }
  if (password.value.length < 8) {
    errorText.innerHTML = `Password length must be greater than 8`;
    password.focus();
    return;
  }
  if(password.value !== password2.value){
    errorText.innerHTML = `Password doesn't match`;
    password2.focus();
    return;
  }
  errorText.innerHTML=``;
  let user={
    username: username.value,
    email: email.value,
    token: generateToken(),
  }
  localStorage.setItem('user',JSON.stringify(user));
  successText.innerHTML=`Successfully signed up`;

  const link = document.createElement('a');
  link.href='./profile.html';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
});



profileLink.addEventListener('click',()=>{
    if(!localStorage.getItem('user')){   //true
        // we are in sign up page 
        // then we click profile link
        profileLink.href='#';
        alert("You don't have account, signup first");
    } else{
        profileLink.href='./profile.html';
    }
});

signUpLink.addEventListener('click',()=>{
    if(localStorage.getItem('user')){
        signUpLink.href='#';
        alert("You already have an account, go to profile");
    } else{
        signUpLink.href='./index.html';
    }
});






















































